### ISSUE TITLE
Review 4: TestimonyList.jsx and NavBar.jsx

### ISSUE THREAD

**Issue by zakgilbert** [alahele/alahele#134]
## Review Branch

review-4
[E10](https://courses.ics.hawaii.edu/ics414f22/morea/review/experience-review-04-setup.html)

## Files to review
* [TestimonyList.jsx](https://github.com/alahele/alahele/blob/main/app/imports/ui/pages/TestimonyList.jsx)
* [NavBar.jsx](https://github.com/alahele/alahele/blob/main/app/imports/ui/components/NavBar.jsx)

## Checklists
* [Architecture](https://github.com/cammoore/campus-cravings/tree/master/checklists/architecture-checklist.md)
* [Design](https://github.com/cammoore/campus-cravings/tree/master/checklists/design-checklist.md)
* [JS](https://github.com/cammoore/campus-cravings/tree/master/checklists/js-checklist.md)
* [React](https://github.com/cammoore/campus-cravings/tree/master/checklists/react-checklist.md)
* [Testing](https://github.com/cammoore/campus-cravings/tree/master/checklists/testing-checklist.md)

## Due date

9/29/2022

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by William-Liang808** [comment]
Testimony.jsx
- L9 Should include a component ID for testcafe to use

NavBar.jsx
- Looks good

**Comment by sle417** [comment]
Testimony.jsx
- Looks Good

NavBar.jsx
- Looks Good

**Comment by cathy-kim95** [comment]
Testimony.jsx

- looks good to me

NavBar.jsx

- looks good to me

**Comment by lisemnilsen** [comment]
TestimonyList.jsx
- Looks good

NavBar.jsx
- Looks good

**Comment by eric-song1773** [comment]
Both TestimonyList.jsx and NavBar.jsx looks good with the current implementation.
