### ISSUE TITLE
Review: UserProfile and CardGrid

### ISSUE THREAD

**Issue by zakgilbert** [alahele/alahele#43]
## Review Branch
[review-1](https://github.com/alahele/alahele/tree/zakg-issue-7)
## Files to review
* [MeasuresGrid.jsx](https://github.com/alahele/alahele/tree/zakg-issue-7/app/imports/ui/components/MeasuresGrid.jsx)
* [UserProfile.jsx](https://github.com/alahele/alahele/tree/zakg-issue-7/app/imports/ui/pages/UserProfile.jsx)
## Checklists
* [Architecture](https://github.com/cammoore/campus-cravings/tree/master/checklists/architecture-checklist.md)
* [Design](https://github.com/cammoore/campus-cravings/tree/master/checklists/design-checklist.md)
* [JS](https://github.com/cammoore/campus-cravings/tree/master/checklists/js-checklist.md)
* [React](https://github.com/cammoore/campus-cravings/tree/master/checklists/react-checklist.md)

**Comment by William-Liang808** [comment]
# **MeasuresGrid.jsx**

Looks good

# **UserProfile.jsx**

line 2 - no need to import style.css as it should be already global. 

# **Both**
Looks like both follow the conventions and requirements from the checklists.

**Comment by cathy-kim95** [comment]
MeasuresGrid.jsx

- JS-08: /** comments

UserProfile.jsx

- JS-08: /** comments

**Comment by eric-song1773** [comment]
MeasuresGrid.jsx
- This file follows all the requirements in checklist.

UserProfile.jsx
- Design-03: Line 2 - Importing style.css is unnecessary since css is already applied without this line.

**Comment by sle417** [comment]
MeasureGrid.jsx
- measure.body prop type not used (?)
UserProfile.jsx
- javadoc comments could help
- general code spacing for cleaner look

**Comment by tineriver** [comment]
MeasuresGrid.jsx
none

UserProfile.jsx
L15-26: Create subcomponent to hold list of measure followed by user
L9: Define constants with useTracker(() => {…
