### ISSUE TITLE
Figure out how to Fetch Bill Data

### ISSUE THREAD

**Issue by zakgilbert** [alahele/alahele#44]
[legtracker-f22](https://github.com/cammoore/legtracker-f22)
@cammore has Implemented a new project template to support the scraped legislator data using meteor. The object of this ticket is to research how we will hydrate our project with the scraped data. If you look at the diff in his latest commits you can see the changes he has made. Next, you have to create a branch and add files he has added to our project. Then push to master.

**Comment by sle417** [comment]
https://raw.githubusercontent.com/cammoore/legtracker-f22/main/app/public/data/measures.json
