### ISSUE TITLE
Create an onExit strategy

### ISSUE THREAD

**Issue by zakgilbert** [alahele/alahele#60]
As of now, when a user exits the application, that user is not logged out. Thus when the user re-enters, they are already logged in, which is good. I'm assuming that if the browser's cookies are cleared, the user will not be logged in the next time the application is accessed. Here's the problem, if the user has login credentials stored in the browser's cookies when the application is accessed, the user is not directed to the homepage, they are directed to the landing. The landing is only for before a user is logged in.

**Comment by sle417** [comment]
I tried to tackle this for about 2-3 hours. It looks like when the user logs in and revisits the site later, it redirects to localhost:3000 despite being signed in, which ends up showing a blank page. I'm not sure where to apply the logic to where if the user is recognized as signed in, that it redirects them to localhost:3000/home instead.

**Comment by sle417** [comment]
![Image](https://user-images.githubusercontent.com/77819979/192456920-9fd84bf6-923f-46c0-9864-71033784d948.png)
